### PR TITLE
100% json and ajax to clear problems log in Visual Code

### PR DESCRIPTION
**Pull request by Siphon880gh**
This will clear your problems log in Visual Code without breaking the extension. 3 files were changed. Hope this helps.
-Weng Fei Fung.

### CODE REVIEW

**Review by BolajiAyodeji — APPROVED** [review]
Thanks for this PR @Siphon880gh
This fixed the console errors!

**Comment by BolajiAyodeji** [comment]
What sort of error should be here? @Siphon880gh
```bash
request.onerror = () => {
    // TODO: Add your on error handler here.
}
```

That should be if the requested JSON returns 404 right?
Some sort of console logs?

**Comment by Siphon880gh** [comment]
Yep, 404 is one use case. I'd use console log.

**Comment by BolajiAyodeji** [comment]
Okay! I used console logs already!
Thank you @Siphon880gh 👍

**Comment by BolajiAyodeji** [comment]
I've sent an upgrade already!! 🔥 
You should update yours

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @Siphon880gh for code

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @Siphon880gh for code

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @Siphon880gh for code

**Pull request merged**
