### PR TITLE
Added 2 quotes

### PR DESCRIPTION
**Pull request by FredAmartey**

### CODE REVIEW

**Comment by FredAmartey** [comment]
Will add more in free time

**Comment by BolajiAyodeji** [comment]
Hello there, thanks for sending in a PR.
Please note: when contributing to an OSS project, add a description to your PR and possible screenshots

**Comment by FredAmartey** [comment]
Im sorry about that. I thought my commit message was the description I needed. Thanks for letting me know. I'm here to learn.

**Comment by BolajiAyodeji** [comment]
> Im sorry about that. I thought my commit message was the description I needed. Thanks for letting me know. I'm here to learn.

Sure it's fine, you committed no offence.
That's why I'm letting you know.
Well done!

**Comment by BolajiAyodeji** [comment]
Hello @FredAmartey, are you still working on this?

**Pull request closed without merging**
