### PR TITLE
Added a few good quotes !!

### PR DESCRIPTION
**Pull request by Ekwuno**

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
This PR is great!
Only that you forgot to remove the `,` after the last quote.
The last quotes don't have `,` after the curly brackets, can you fix that first?

**Comment by Ekwuno** [comment]
I have done it !

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @Ekwuno for code

**Comment by BolajiAyodeji** [comment]
@allcontributors please add @Ekwuno for code

**Pull request merged**
